### ISSUE TITLE
[Solution] "'NODE_OPTIONS' is not recognized as an internal or external command, bla bla

### ISSUE THREAD

**Issue by RangerCoder99** [imranhsayed/nextjs-headless-wordpress#35]
If anyone else getting this error: 
'NODE_OPTIONS' is not recognized as an internal or external command, bla bla 

Here is the solution: 
**1.** **Install the cross-env package** ('npm i cross-env' or 'yarn add cross-env')
**2.** **Replace the dev script in the package.json file with:**
`"dev": "cross-env NODE_OPTIONS='--inspect' next",`

**Comment by imranhsayed** [comment]
Thanks @RangerCoder99 👍
