### ISSUE TITLE
GraphQLError: Syntax Error: Unexpected Name "headerMenus".

### ISSUE THREAD

**Issue by TechStacker** [imranhsayed/nextjs-headless-wordpress#55]
Hi, I've followed your great YouTube tutorials, and everything worked until video “7: getStaticProps Nextjs” where I get this error:

````
Server Error
GraphQLError: Syntax Error: Unexpected Name "headerMenus".

This error happened while generating the page. Any console logs will be displayed in the terminal window.
````

The issue is on on line 4 in `get-menus.js` (`export const GET_MENUS = gql`)

Here's my entire `get-menus.js` file: 

````
import { gql } from "@apollo/client";
import MenuFragment from "./fragments/menus";

export const GET_MENUS = gql`

headerMenus: menuItems(where: {location: HCMS_MENU_HEADER, parentId: "0"}) {
  edges {
    node {
      ...MenuFragment
      childItems {
        edges {
          node {
            ...MenuFragment
          }
        }
      }
    }
  }
}
footerMenus: menuItems(where: {location: HCMS_MENU_FOOTER, parentId: "0"}) {
  edges {
    node {
      ...MenuFragment
    }
  }
  
  ${MenuFragment}
`;

````

There are a couple of people in the comments section on that video that have the same problem. 

What am I doing wrong?

**Comment by imranhsayed** [comment]
Have you installed and activated Headless CMS WordPress plugin and set up menus?
Please test the query in WordPress GraphiQL playground

**Comment by TechStacker** [comment]
There were some missing pieces in video 6 & 7, but the working code in the get-menus.js file https://raw.githubusercontent.com/imranhsayed/nextjs-headless-wordpress/main/frontend/src/queries/get-menus.js

**Comment by deopronet** [comment]
everything we're doing still not work.... can you provide something about that?

**Comment by deopronet** [comment]
I got the some problem.... fixed now ! 
 
Just make sure to select client from ApolloClient when you're taping your code

 const { data, loading, networkStatus } = await **client**.query({
    query: GET_MENUS
  });

**Comment by touseefcodes** [comment]
I am facing the same problem, when i run the same query on the qraphiql, it works, but it gives out the `GraphQLError: Syntax Error: Unexpected Name "headerMenus".` error when I run it from the NextJS. 
![graph](https://user-images.githubusercontent.com/81577619/156200956-4e3b8ff8-af11-4a6b-9099-51884b7faebb.png)

**Comment by paulonova** [comment]
I am facing the same problem, when i run the same query on the qraphiql, it works, but it gives out the GraphQLError: Syntax Error: Unexpected Name "headerMenus". error when I run it from the NextJS.
graph

Until now I dont know what to do! Can please some one help with some solution? 

Thanks

**Comment by jigneshdpanchal** [comment]
replace your code with the following one and your error will be solved as mine...

export const GET_MENUS = gql`

**query{**
headerMenus: menuItems(where: {location: HCMS_MENU_HEADER, parentId: "0"}) {
  edges {
    node {
      ...MenuFragment
      childItems {
        edges {
          node {
            ...MenuFragment
          }
        }
      }
    }
  }
}

footerMenus: menuItems(where: {location: HCMS_MENU_FOOTER, parentId: "0"}) {
  edges {
    node {
      ...MenuFragment
    }
  }
}
**}**
${MenuFragment}
`
