### ISSUE TITLE
Minor Seo Bug

### ISSUE THREAD

**Issue by Bowriverstudio** [imranhsayed/nextjs-headless-wordpress#68]
Hello Imranhsayed, thank you for the repo and lessons.

https://github.com/imranhsayed/nextjs-headless-wordpress/blob/main/frontend/src/components/seo/index.js

The fields have the following values:

 metaRobotsNoindex, // index | noindex
    metaRobotsNofollow, // follow | nofollow

So in the component, it should be

        noindex={metaRobotsNoindex === "noindex"}
        nofollow={metaRobotsNofollow === "nofollow"}

**Comment by riccardodicurti** [comment]
pull request: https://github.com/imranhsayed/nextjs-headless-wordpress/pull/71

**Comment by imranhsayed** [comment]
@riccardodicurti This is merged . Thank you for the contribution
